name: Kint setup
inputs:
  php-version:
    required: true
  php-coverage:
    required: false
    default: none
  php-ini-values:
    required: false
    default: ''
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: latest
        cache: npm
    - uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        coverage: ${{ inputs.php-coverage }}
        ini-values: ${{ inputs.php-ini-values }}
    - run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      shell: bash
      id: composer-cache
    - uses: actions/cache@v4
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-${{ inputs.php-version < 8.1 }}-${{ hashFiles('./composer.lock') }}
    # On old versions we only run tests so strip everything else out
    - run: |
        composer remove --dev $(composer show --no-interaction --locked --name-only --direct)
        composer config platform.php 7.4
        composer require --dev phpunit/phpunit ^9
      shell: bash
      if: inputs.php-version < 8.1
    # On new versions just composer install
    - run: composer install
      shell: bash
      if: inputs.php-version >= 8.1
